# Generated by Django 3.2.12 on 2022-11-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_title',
        ),
    ]
